version: "3.3"
services:
  node_angular:
    user: node:node
    build:
      context: frontend
      dockerfile: Dockerfile-dev
      args:
        USER_UID: ${USER_UID:-1000}
    volumes:
      - /usr/src/app/node_modules
      - ./frontend/videoclub:/usr/src/app

  angular:
    image: nginx
    volumes:
      - ./frontend/config/default.conf.dev:/etc/nginx/conf.d/default.conf
      - ./frontend/config/nginx.conf:/etc/nginx/nginx.conf
      - ./docs/api_doc:/var/www/html
    depends_on:
      - node_angular
    environment:
      - PRODUCTION=${PRODUCTION:-false}
      - APP_DOMAIN=${APP_DOMAIN:-localhost}

  mongo:
    volumes:
      - ./db:/data/db

  processor:
    command: npm run dev
    environment:
      - PRODUCTION=${PRODUCTION:-false}
      - APP_DOMAIN=${APP_DOMAIN:-localhost}
      - NODE_ENV=${PRODUCTION:-false}
    ports:
      - ${BACKEND_PORT:-8080}:3000
    volumes:
      - /usr/app/node_modules
      - ./backend:/usr/app
