version: "3.6"
services:
  node_angular:
    user: node:node
    build:
      context: frontend
      dockerfile: Dockerfile-dev
      args:
        USER_UID: ${USER_UID:-1000}
    volumes:
      - /usr/src/app/node_modules
      - ./frontend/videoclub:/usr/src/app

  angular:
    image: nginx
    volumes:
      - ./config/default.conf.dev:/etc/nginx/conf.d/default.conf
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${FRONTEND_PORT:-9080}:80
    depends_on:
      - node_angular
    environment:
      - PRODUCTION=${PRODUCTION:-false}
      - APP_DOMAIN=${APP_DOMAIN:-localhost}
  
  mongo:
    volumes:
      - ./db:/data/db
  
  processor:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run dev
    depends_on:
      - mongo
    environment:
      - PRODUCTION=${PRODUCTION:-false}
      - APP_DOMAIN=${APP_DOMAIN:-localhost}
      - NODE_ENV=${PRODUCTION:-false}